services:
  mysql:
    image: mysql:8.0 # LTS version of MySQL
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: social-media_training
      MYSQL_USER: springUser
      MYSQL_PASSWORD: thePassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: